# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This install mumps, ipopt via coindbrew and casadi, bipedal-locomotion-framework via robotology-superbuild
  build-conda-coinbrew-superbuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true

    - name: Dependencies
      shell: bash -l {0}
      run: |
        mamba install cmake compilers make catch2 ninja pkg-config ace asio boost eigen irrlicht gazebo glew glfw gsl libjpeg-turbo libmatio libode libxml2 opencv pkg-config portaudio qt sdl sdl2 sqlite tinyxml spdlog expat-cos6-x86_64 freeglut libdc1394 libselinux-cos6-x86_64 libxau-cos6-x86_64 libxcb-cos6-x86_64 libxdamage-cos6-x86_64 libxext-cos6-x86_64 libxfixes-cos6-x86_64 libxxf86vm-cos6-x86_64 mesalib mesa-libgl-cos6-x86_64 spdlog nlohmann_json valgrind
        
    - name: Coinbrew
      shell: bash -l {0}
      run: |
        mkdir CoinIpopt 
        cd CoinIpopt
        wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
        chmod u+x coinbrew
        ./coinbrew build Ipopt --prefix=install --test --no-prompt --verbosity=3
        ./coinbrew install Ipopt --no-prompt

    - name: Install blf via robotology-superbuild
      shell: bash -l {0}
      run: |
        export IPOPT_DIR=${GITHUB_WORKSPACE}/CoinIpopt/install
        export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${IPOPT_DIR}/lib/pkgconfig
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${IPOPT_DIR}/lib
        export PATH=${PATH}:${IPOPT_DIR}/lib
        # Conda-specific step
        export LDFLAGS="$LDFLAGS -Wl,-rpath,${IPOPT_DIR}/lib" 
        export LDFLAGS="$LDFLAGS -Wl,-rpath-link,${IPOPT_DIR}/lib"
        git clone https://github.com/robotology/robotology-superbuild
        cd robotology-superbuild
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DNON_INTERACTIVE_BUILD:BOOL=ON -DROBOTOLOGY_PROJECT_TAGS:STRING=Unstable -DROBOTOLOGY_USES_GAZEBO:BOOL=OFF -DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=ON -DROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS:BOOL=ON ..
        cmake --build . --target bipedal-locomotion-framework
        cd ../src/bipedal-locomotion-framework
        # git checkout debug/241
        cd ../../build/src/bipedal-locomotion-framework
        cmake -DBUILD_TESTING=ON -DFRAMEWORK_RUN_Valgrind_tests:BOOL=ON .
        cmake --build . --target TimeVaryingDCMPlannerUnitTests
        ctest -VV --repeat-until-fail 10 -R TimeVaryingDCMPlannerUnitTests

  # This install mumps, ipopt via conda-forge and casadi, bipedal-locomotion-framework via robotology-superbuild
  build-conda-superbuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true

    - name: Dependencies
      shell: bash -l {0}
      run: |
        mamba install cmake compilers make catch2 ninja pkg-config ace asio boost eigen irrlicht gazebo glew glfw gsl ipopt libjpeg-turbo libmatio libode libxml2 opencv pkg-config portaudio qt sdl sdl2 sqlite tinyxml spdlog expat-cos6-x86_64 freeglut libdc1394 libselinux-cos6-x86_64 libxau-cos6-x86_64 libxcb-cos6-x86_64 libxdamage-cos6-x86_64 libxext-cos6-x86_64 libxfixes-cos6-x86_64 libxxf86vm-cos6-x86_64 mesalib mesa-libgl-cos6-x86_64 nlohmann_json valgrind
        
    - name: Install blf via robotology-superbuild
      shell: bash -l {0}
      run: |
        git clone https://github.com/robotology/robotology-superbuild
        cd robotology-superbuild
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DNON_INTERACTIVE_BUILD:BOOL=ON -DROBOTOLOGY_PROJECT_TAGS:STRING=Unstable -DROBOTOLOGY_USES_GAZEBO:BOOL=OFF -DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=ON -DROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS:BOOL=ON ..
        cmake --build . --target bipedal-locomotion-framework
        cd ../src/bipedal-locomotion-framework
        # git checkout debug/241
        cd ../../build/src/bipedal-locomotion-framework
        cmake -DBUILD_TESTING=ON -DFRAMEWORK_RUN_Valgrind_tests:BOOL=ON .
        cmake --build . --target TimeVaryingDCMPlannerUnitTests
        ctest -VV --repeat-until-fail 10 -R TimeVaryingDCMPlannerUnitTests
        
  # This install mumps, ipopt, casadi via conda-forge, and bipedal-locomotion-framework manually
  build-conda-manual:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true

    - name: Dependencies
      shell: bash -l {0}
      run: |
        mamba install -c robotology cmake compilers make ninja pkg-config idyntree yarp matio-cpp lie-group-controllers eigen qhull casadi cppad manif spdlog catch2 nlohmann_json valgrind
        
    - name: Install blf manually
      shell: bash -l {0}
      run: |
        git clone https://github.com/dic-iit/bipedal-locomotion-framework
        cd bipedal-locomotion-framework
        # git checkout debug/241
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DBUILD_TESTING=ON -DFRAMEWORK_RUN_Valgrind_tests:BOOL=ON ..
        cmake --build . --target TimeVaryingDCMPlannerUnitTests
        ctest -VV --repeat-until-fail 10 -R TimeVaryingDCMPlannerUnitTests
   
   
  # This install mumps, ipopt via coindbrew and casadi, bipedal-locomotion-framework via robotology-superbuild
  build-apt-coinbrew-superbuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    steps:
    - name: Dependencies (without ipopt)
      run: |
        sudo apt-get install -y ninja-build build-essential pkg-config cmake cmake-curses-gui freeglut3-dev git libace-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libdc1394-22-dev libedit-dev libeigen3-dev libgsl0-dev libjpeg-dev liblua5.1-dev libode-dev libopencv-dev libsdl1.2-dev libtinyxml-dev libv4l-dev libxml2-dev lua5.1 portaudio19-dev qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings qml-module-qtmultimedia qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-window2 qml-module-qtquick2 qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev swig libspdlog-dev libmatio-dev libirrlicht-dev nlohmann-json3-dev valgrind
        git clone https://github.com/catchorg/Catch2
        cd Catch2 
        git checkout v2.13.4
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . 
        sudo cmake --install . 

        

    - name: Coinbrew
      run: |
        mkdir CoinIpopt 
        cd CoinIpopt
        wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
        chmod u+x coinbrew
        ./coinbrew build Ipopt --prefix=install --test --no-prompt --verbosity=3
        ./coinbrew install Ipopt --no-prompt

    - name: Install blf via robotology-superbuild
      run: |
        export IPOPT_DIR=${GITHUB_WORKSPACE}/CoinIpopt/install
        export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:${IPOPT_DIR}/lib/pkgconfig
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${IPOPT_DIR}/lib
        export PATH=${PATH}:${IPOPT_DIR}/lib
        git clone https://github.com/robotology/robotology-superbuild
        cd robotology-superbuild
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DNON_INTERACTIVE_BUILD:BOOL=ON -DROBOTOLOGY_PROJECT_TAGS:STRING=Unstable -DROBOTOLOGY_USES_GAZEBO:BOOL=OFF -DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=ON -DROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS:BOOL=ON ..
        cmake --build . --target bipedal-locomotion-framework
        cd ../src/bipedal-locomotion-framework
        # git checkout debug/241
        cd ../../build/src/bipedal-locomotion-framework
        cmake -DBUILD_TESTING=ON -DFRAMEWORK_RUN_Valgrind_tests:BOOL=ON .
        cmake --build . --target TimeVaryingDCMPlannerUnitTests
        ctest -VV --repeat-until-fail 10 -R TimeVaryingDCMPlannerUnitTests
        
        
  # This install mumps, ipopt via apt and casadi, bipedal-locomotion-framework via robotology-superbuild
  build-apt-superbuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    steps:
    - name: Dependencies
      run: |
        sudo apt-get install -y ninja-build build-essential pkg-config cmake cmake-curses-gui coinor-libipopt-dev freeglut3-dev git libace-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libdc1394-22-dev libedit-dev libeigen3-dev libgsl0-dev libjpeg-dev liblua5.1-dev libode-dev libopencv-dev libsdl1.2-dev libtinyxml-dev libv4l-dev libxml2-dev lua5.1 portaudio19-dev qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings qml-module-qtmultimedia qml-module-qtquick-controls qml-module-qtquick-dialogs qml-module-qtquick-window2 qml-module-qtquick2 qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev swig libspdlog-dev libmatio-dev libirrlicht-dev nlohmann-json3-dev valgrind
        git clone https://github.com/catchorg/Catch2
        cd Catch2 
        git checkout v2.13.4
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . 
        sudo cmake --install . 

    - name: Install blf via robotology-superbuild
      run: |
        git clone https://github.com/robotology/robotology-superbuild
        cd robotology-superbuild
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -GNinja -DNON_INTERACTIVE_BUILD:BOOL=ON  -DROBOTOLOGY_PROJECT_TAGS:STRING=Unstable -DROBOTOLOGY_USES_GAZEBO:BOOL=OFF -DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=ON -DROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS:BOOL=ON ..
        cmake --build . --target bipedal-locomotion-framework
        cd ../src/bipedal-locomotion-framework
        # git checkout debug/241
        cd ../../build/src/bipedal-locomotion-framework
        cmake -DBUILD_TESTING=ON -DFRAMEWORK_RUN_Valgrind_tests:BOOL=ON .
        cmake --build . --target TimeVaryingDCMPlannerUnitTests
        ctest -VV --repeat-until-fail 10 -R TimeVaryingDCMPlannerUnitTests
